server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /img/ {
        alias /data/;  # 指定静态文件的实际路径
     	expires 30d;
   	add_header Cache-Control "public";
	gzip on;
	gzip_types text/css application/javascript image/svg+xml;
	gzip_min_length 1000;
    }

}

