# DataSource Config
server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 替换成你的MySQL密码
    url: jdbc:mysql://localhost:3306/bug_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456  # 改成你的MySQL密码

## MyBatisPlus配置
#mybatis-plus:
#  configuration:
#    # 开启驼峰命名转换
#    map-underscore-to-camel-case: true
#    # 显示SQL日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
